### ISSUE TITLE
triggerLatch() is inverted

### ISSUE THREAD

**Issue by nelisbrink** [RobTillaart/MCP_DAC#21]
I am working with the MCP4822 and according to the datasheet the LDAC is a NOT pin. So, quoting from the datasheet: 

"By bringing down the LDAC pin to a **low** state, the contents
stored in the DAC’s input registers are transferred
into the DAC’s output registers (VOUT), and both VOUTA
and VOUTB are updated at the same time."

So should you not init the LDAC pin as high and toggle low when you want to latch? I see it is inverted in your library...

**Comment by RobTillaart** [comment]
Thanks for this issue.
Sounds like a serious bug so I will look into it asap.

**Comment by RobTillaart** [comment]
code snippet from latest version, so yes inverted (apparently it was not tested enough)
```cpp

void MCP_DAC::setLatchPin(uint8_t latchPin)
{
  _latchPin = latchPin;
  pinMode(_latchPin, OUTPUT);
  digitalWrite(_latchPin, LOW);
}

void MCP_DAC::triggerLatch()
{
  if (_latchPin != 255)
  {
    digitalWrite(_latchPin, HIGH);
    delayMicroseconds(1);     // 100 ns - Page 7
    digitalWrite(_latchPin, LOW);
  }
}
```

Handshake from datasheet page 7
![image](https://user-images.githubusercontent.com/462844/227154517-015c1d47-1bd0-46a0-bc9a-de36cd4db581.png)

**Comment by RobTillaart** [comment]
Created  a develop branch to solve the invert problem (+ fix for setPercentage() + refactor).
Can you give it a try?

**Comment by nelisbrink** [comment]
I can confirm, the latch trigger is working correctly now :+1:

**Comment by RobTillaart** [comment]
@nelisbrink 
Thanks for testing, I will merge the PR !
