### ISSUE TITLE
Cannot run unless SPI.begin() is called

### ISSUE THREAD

**Issue by CraigMason** [RobTillaart/MCP_DAC#3]
Hello,

MCP4911
Arduino Nano 33 BLE

Started integrating this library today instead of manually setting up SPI for controlling a 4911. I note that I cannot get the library to work unless I call `SPI.begin()` within my `setup()`. All calls to `analogWrite` hang.

I hacked in a couple of checks to the constructor to see if [SPI.begin()](https://github.com/RobTillaart/MCP_DAC/blob/master/MCP_DAC.cpp#L28) is called, and it appears to be, but regardless, without `SPI.begin()` in my `setup()`, the SPI comms hang.

Tested using [MCP4921_test.ino](https://github.com/RobTillaart/MCP_DAC/blob/master/examples/MCP4921_test/MCP4921_test.ino) by changing [14](https://github.com/RobTillaart/MCP_DAC/blob/master/examples/MCP4921_test/MCP4921_test.ino#L14) to `MCP4911 MCP;` and also removed the performance test.

Not sure if it's more of an upstream issue, but wanted to log it.

**Comment by RobTillaart** [comment]
Interesting find. 
Will try to recreate the issue and investigate.
Might take a few days as I might need to order an MCP4911.

**Comment by RobTillaart** [comment]
A first test on an UNO (no nano BLE to test) with no DAC connected worked fine except for the values of course. 
(no need to connect as SPI just bangs the bits anyway) 

Some reading about the nano33 BLE learned me (correct me If I'm wrong) that it uses mbedOS. 
I must admit that I have practical no experience with this OS, so SPI might just behave slightly differently.
My hypothesis is that the execution of the constructor is either delayed by the compiler or maybe parts are optimized in such a way that the SPI initialization is either too late or even "optimized away". Have too little knowledge about the mbedOS /compiler to say.

A way to prevent this and make the SPI.begin more explicit is to move it from the constructor to the **begin()** command
Could you test if that works on mbedOS?

Could you change the begin function in the .cpp file to include the **SPI begin()** line
```cpp
void MCP_DAC::begin(uint8_t select)
{
  _select = select;
  pinMode(_select, OUTPUT);
  digitalWrite(_select, HIGH);
  if (_hwSPI) SPI.begin();
}
```

On UNO this works.

thanks

**Comment by RobTillaart** [comment]
Created a develop branch in which the **SPI.begin()** move is prepared (+ some minor refactor)
Think it is a good idea anyway

**Comment by CraigMason** [comment]
> Some reading about the nano33 BLE learned me (correct me If I'm wrong) that it uses mbedOS.
I must admit that I have practical no experience with this OS, so SPI might just behave slightly differently.

I'm in the same position - actually it's my first time using the nano33 BLE.

I can confirm that the `devel` branch works as expected. But I'm still a bit puzzles as to why it doesn't work when in the constructor. I'm sure there are countless other libraries that are initialising SPI in this way.

Thanks for looking into it so quickly.

**Comment by RobTillaart** [comment]
Possible explanation is that the compiler decides **when** to execute the code from the constructor. Most people (including me) assume it is done before **setup()** is called, but that does not need to be true. Theoretically it can be postponed until the first usage of an instance. 
Another cause could be some premature optimization.

In both cases one need to dive into the generated assembly to see what really happens.

Thanks for your quick test, I will merge the branch right away and publish new release.
If there are other issues, please let me know!

**Comment by RobTillaart** [comment]
Develop merged into master so I consider this one solved.
Otherwise feel free to reopen the issue.
