### ISSUE TITLE
Can we use hardware SPI on V_SPI on ESP32 ?

### ISSUE THREAD

**Issue by HankLloydRight** [RobTillaart/MCP_DAC#5]
Rob, 

 Thank you for all your awesome libraries! I've used several already. 

 I'm building an ESP32 project and using this MCP_DAC library with great results so far.

 But I can't seem to get **_hwSPI** enabled.  I think the library is hard-coded by default for **H_SPI** when it runs on ESP32, so on **V_SPI** it can only run in software SPI mode.   Do you have any ideas on how to change the code to run on **V_SPI** in hardware SPI mode? 

Here's a good page that discusses the different SPI buses on ESP32: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/spi_master.html#gpio-matrix-and-io-mux

Even when I specify the **V_SPI (SPI3)** IO_MUX pins  in the constructor (23,18), that forces it to software SPI mode.  If I do not call the constructor with the pins, it goes into hardware SPI mode, but on **H_SPI (SPI2).** 

I hope this is clear. 

Thank you.

**Comment by RobTillaart** [comment]
Hi Hank,

The class only supports HSPI in hardware as I used the Arduino SPI class to be UNO (etc) compatible
It is a consequence of "organic growth" of the library, features are added (if possible) on a need to basis. 

Think it is not too difficult to change the class to "support" VSPI  so I will create a test branch which you can verify.
I do not have hardware nearby to check it on short term.

**Comment by HankLloydRight** [comment]
Rob,

 Thank you for your efforts! 
  I'd be very happy to test any branch you create to make hardware V_SPI available on ESP32!

-Hank

**Comment by RobTillaart** [comment]
There now exist a branch called **experimental** which has a SPIClass added into it
this is initialized in the begin() function  to VSPI  (line 50 something)
you should be able to set SPI (for UNO) HSPI and VSPI 

not tested and hoping it works 😀

**Comment by RobTillaart** [comment]
If this works I can think about a clean way to switch between SPI, VSPI and HSPI.

In a future version it might be able to change the default GPIO pins of  VSPI/HSPI pins.

**Comment by RobTillaart** [comment]
experimental branch updated 
- bool **_useHSPI** to hold the flag VSPI / HSPI
- select functions for ESP32 to set this var
- begin() adjusted to use the flag.
-

**Comment by HankLloydRight** [comment]
Hi Rob,
 Thank you for your prompt changes!

 Ok, I installed the latest  branch, and I'm not getting any DAC output.

To enable _hwSPI, I changed my constructor from:
```
const uint8_t iMOSI=23,iSCK=18; // V_SPI pins on ESP32 -- macros 'MOSI' and 'SCK' are already defined somewhere else
MCP4922 MCPxy(iMOSI,iSCK),MCPd1(iMOSI,iSCK),MCPd2(iMOSI,iSCK);
```
to:
`MCP4922 MCPxy,MCPd1,MCPd2;`

and in setup() I'm initializing three DACs like this:
```
        const uint8_t XYDAC=5,DAC_1=16,DAC_2=4,LATCH=17; // DAC chip select #s for SPI
	MCPxy.selectVSPI();
	MCPd1.selectVSPI();
	MCPd2.selectVSPI();
	MCPxy.begin(XYDAC);
	MCPd1.begin(DAC_1);
	MCPd2.begin(DAC_2);
```

Everything compiled and ran as usual, but no DAC output. 

I've also tried this, but still doesn't work:
```
#undef MOSI
#undef MISO
#undef SCK
#define MOSI 23
#define MISO 19
#define SCK 18

```

Here's some serial debugging output:
> XYDAC usesHWSPI(): 1  // isVSPI():1 Speed: 40000000
> DAC1 usesHWSPI(): 1   // isVSPI():1 Speed: 40000000
> DAC2 usesHWSPI(): 1   // isVSPI():1 Speed: 40000000
> SPI MISO:19 MOSI:23 SCK: 18 ESP32: 1


Any ideas?

**Comment by RobTillaart** [comment]
If you do not set VSPI but uses the default
```cpp
	// MCPxy.selectVSPI();
	// MCPd1.selectVSPI();
	// MCPd2.selectVSPI();
```
does the HSPI work or not?

**Comment by RobTillaart** [comment]
Please try to replace the **begin()** function in the .cpp file with this code.
It explicitly sets the default pins.

```cpp
void MCP_DAC::begin(uint8_t select)
{
  _select = select;
  pinMode(_select, OUTPUT);
  digitalWrite(_select, HIGH);
  if (_hwSPI)
  {
    #if defined(ESP32)
    if (_useHSPI)
    {
      mySPI = new SPIClass(HSPI);
      mySPI->begin(14, 12, 13, _select);
    }
    else
    {
      mySPI = new SPIClass(VSPI);
      mySPI->begin(18, 19, 23, _select);
    }
    #else
    mySPI = new SPIClass(SPI);
    mySPI->begin();
    #endif
  }
}
```

**Comment by HankLloydRight** [comment]
Ok, that last change works. Thank you! 

Looks like my project is now using _hwSPI on the VSPI bus. 
I am getting correct output on all three DACs.

The only thing is that it's much slower now.  I'm sending 5 points to the DACs on each iteration of the main loop() -- X,Y position and RGB color.  

With this _hwSPI enabled, I'm getting about 21,000 loop iterations (or about 100,000 DAC points) sent per second.  With the old way (not using _hwSPI), I was getting about 28,500 loop iterations per second (or about 150,000 points) sent per second.  

Everything I've read says that HW SPI should be much faster than SW SPI.  I don't know enough how to diagnose this further.

By the way, I can't test using the HSPI bus since my project is already built into a PCB and it uses the VSPI pins.

Thank you again for all your great work (not just here).

-Hank

**Comment by HankLloydRight** [comment]
Also, by the way, I made one small modification to your code (see below)
With this single if statement added, the latch is only triggered if you've previously set **.setLatchPin(LATCH)** to a value.
So you can turn latching on or off by just setting or not setting the latch pin. 

```c++
void MCP_DAC::triggerLatch()
{
  if(_latchPin!=255)
  {
	  digitalWrite(_latchPin, HIGH);
	  delayMicroseconds(1);     // 100 ns - Page 7
	  digitalWrite(_latchPin, LOW);
 }
}

```

**Comment by RobTillaart** [comment]
pushed the last change into experimental.

> Everything I've read says that HW SPI should be much faster than SW SPI.

A plausible cause is this line ~150
```cpp
    mySPI->beginTransaction(SPISettings(_SPIspeed, MSBFIRST, SPI_MODE0));
```
for every transaction the settings are made again and again.

If the library would create a ```SPISettings fast(_SPIspeed, MSBFIRST, SPI_MODE0);``` somewhere and do the transactions as
```cpp
    mySPI->beginTransaction(fast);
```
will probably be more efficient. 

I will try to patch the experimental branch further...

**Comment by HankLloydRight** [comment]
Cool, thank you again!

Ok, I found the problem with the missing pin settings. I dug down and found the pins_arduino.h file for my ESP32 variant (lolin32) and this was the code:
```c++
//VSPI
/*
static const uint8_t SS    = 5;
static const uint8_t MOSI  = 23;
static const uint8_t MISO  = 19;
static const uint8_t SCK   = 18;
*/

//HSPI
static const uint8_t SS    = 15;
static const uint8_t MOSI  = 13; //SDI
static const uint8_t MISO  = 12; // unused
static const uint8_t SCK   = 14; //Clock
```

So I changed it to:

```c++
//VSPI
static const uint8_t SS    = 5;
static const uint8_t MOSI  = 23;
static const uint8_t MISO  = 19;
static const uint8_t SCK   = 18;


//HSPI
/*
static const uint8_t SS    = 15;
static const uint8_t MOSI  = 13; //SDI
static const uint8_t MISO  = 12; // unused
static const uint8_t SCK   = 14; //Clock
*/
```

I then reverted back to your original .begin() method, and it now works as you intended. 

```c++
void MCP_DAC::begin(uint8_t select)
{
  _select = select;
  pinMode(_select, OUTPUT);
  digitalWrite(_select, HIGH);
  if (_hwSPI)
  {
    #if defined(ESP32)
    if (_useHSPI) mySPI = new SPIClass(HSPI);
    else          mySPI = new SPIClass(VSPI);
    #else
    mySPI = new SPIClass(SPI);
    #endif
    mySPI->begin();
  }
}
```
There should be a better way  in **pins_arduino.h** for ESP32 to use both SPI buses, but at least now it's set up to us VSPI for my needs.  It is still much slower than the software SPI, but at least this solves that problem from earlier.

**Comment by RobTillaart** [comment]
added a patch for the SPI settings in the experimental branch.
Please give it a try to see if performance improves by use a settings variable.

**Comment by RobTillaart** [comment]
> .... pins_arduino.h  ....

Good to hear you found this and it works for you.

However I cannot change the **pins_arduino.h** file and more important the future goal is to be able to set all possible GPIO pins for the hardware SPI of the ESP32 (both HSPI and VSPI). 

With that in mind the version that sets the pins explicitly is a step in the right direction. The current API is not suitable. 
There needs to be more parameters something like  **begin(clock, miso, mosi, select, bool HWSPI/SWSPI, bool HSPI/VSPI)**

maybe even SPIspeed should be in the paramlist?

**Comment by RobTillaart** [comment]
Performance test on UNO  - no need to add the device as communication to the MCP_DAC is one way 

**setting SPISettings over and over again**
```
4095 x MCP.analogWrite():	92812	22.66
4095 x MCP.fastWriteA():	77756	18.98
```


**prepare SPISettings in a var**
```
4095 x MCP.analogWrite():	74540	18.20
4095 x MCP.fastWriteA():	59480	14.52
```

20~25% faster on an UNO, so I expect it could be faster on an ESP32 too

**Comment by HankLloydRight** [comment]
> With that in mind the version that sets the pins explicitly is a step in the right direction.

Oh, I agree!  Having the HSPI/VSPI hard coded in **pins_arduino.h** is a bad way to do it.  Your method is better, but also allowing overrides for future hardware configurations.   It was a little confusing at first that in order to enable _hwSPI that I had to change the constructor to remove the SPI pin parameters.   I like your idea of putting it all in the .begin() call. 

I tested the new **_fast** variable, and unfortunately the speed is about the same as before.  The DACs are receiving and sending out all the right data, but it's much faster in software SPI mode.  

And about SPISpeed, I've been testing that also, and I see almost no change in application speed.  The slowest part of the loop is sending the data to the DACs.. well, it's not even that, as the performance does not change when the DACs are not connected. So it's all internal to the ESP32.  So even on lower SPISpeed settings, the bottleneck is the code to push the values to the SPI bus. 


-Hank

**Comment by RobTillaart** [comment]
> but it's much faster in software SPI mode.

the software SPI coded in this library does (1) not have the transaction part, and (2) It does not return a value (where the SPI-transfer does implement this).

In fact (2) is not true, by rewriting the sw_SPI transfer as void one might even win a few clocks.. (please try - patch .h file too) 

```cpp
void MCP_DAC::swSPI_transfer(uint8_t val)
{
  for (uint8_t mask = 0x80; mask; mask >>= 1)
  {
    digitalWrite(_dataOut,(val & mask) != 0);
    digitalWrite(_clock, HIGH);
    digitalWrite(_clock, LOW);
  }
}
```

**Comment by RobTillaart** [comment]
> I tested the new _fast variable, and unfortunately the speed is about the same as before. 

On UNO there is a gain and no degradation for ESP==> so I think it should be kept :)

**Comment by HankLloydRight** [comment]
> In fact (2) is not true, by rewriting the sw_SPI transfer as void one might even win a few clocks.. (please try - patch .h file too)

I patched both files and no change in performance.  But thank you for keep trying!

I really appreciate your deep dive on this for me.

**Comment by RobTillaart** [comment]
last for today - on UNO it gains ~2%

```cpp
uint8_t  MCP_DAC::swSPI_transfer(uint8_t val)
{
  for (uint8_t mask = 0x80; mask; mask >>= 1)
  {
    digitalWrite(_dataOut, (val & mask));  //  <<<< removed compare with zero
    digitalWrite(_clock, HIGH);
    digitalWrite(_clock, LOW);
  }
  return 0;
}
```

**Comment by RobTillaart** [comment]
> I really appreciate your deep dive on this for me.

You're welcome, it improves the library and it is sort of fun

**Comment by RobTillaart** [comment]
> Also, by the way, I made one small modification to your code (see below)
> With this single if statement added, the latch is only triggered if you've previously set **.setLatchPin(LATCH)** to a value.
> So you can turn latching on or off by just setting or not setting the latch pin.
> 
> ```c++
> void MCP_DAC::triggerLatch()
> {
>   if(_latchPin!=255)
>   {
> 	  digitalWrite(_latchPin, HIGH);
> 	  delayMicroseconds(1);     // 100 ns - Page 7
> 	  digitalWrite(_latchPin, LOW);
>  }
> }
> ```

Will be included in next version too, thx

**Comment by RobTillaart** [comment]
local vars in swSPI gains another ~0.75% on the UNO, please test with ESP32    (in total ~3%)

```cpp
// MSBFIRST
uint8_t MCP_DAC::swSPI_transfer(uint8_t val)
{
  uint8_t clk = _clock;
  uint8_t dao = _dataOut;
  for (uint8_t mask = 0x80; mask; mask >>= 1)
  {
    digitalWrite(dao, (val & mask));
    digitalWrite(clk, HIGH);
    digitalWrite(clk, LOW);
  }
  return 0;
}
```

**Comment by HankLloydRight** [comment]
> ```c++
>   digitalWrite(_dataOut, (val & mask));  //  <<<< removed compare with zero
> ```

Wow, this made about a 5% improvement in performance.  Nice! 

What was the function of the  compare with zero ?

Previously I was getting about  28,500 iterations per second. With this one change, it's now about 29,960 iterations.
My goal was 30,000 points per second, so I'm so so close!  :)

**Comment by RobTillaart** [comment]
>  What was the function of the compare with zero ?

Get a nice true / false  == 1 / 0 - however **digitalWrite()** just checks for 0, all other are 1

**Comment by RobTillaart** [comment]
>  My goal was 30,000 points per second, so I'm so so close! :)

Did you test the local vars variant already? (previous post)

**Comment by HankLloydRight** [comment]
Just testing it now-- another decent bump up to 30,400 pps.  Win! 

You are the best. Can I buy you a beer or something?

**Comment by RobTillaart** [comment]
> Just testing it now-- another decent bump up to 30,400 pps. Win!

That's a nice moment to stop,

> You are the best. Can I buy you a beer or something?

Donate to a charity of your choice, there are bigger problems than squeezing performance :)

You helped to make the lib faster, that's cool in itself.
Now some time to make it 'clean code' again

**Comment by RobTillaart** [comment]
Hi Hank,

Have you tried to use VSPI (hardware SPI ) and then **setSPIspeed(32000000)** ?

default the SPI is set to 16M, I never tried to go beyond that as most of my experiments are UNO based

**Comment by HankLloydRight** [comment]
I've been setting the SPI speed to the max ESP32 will support: 40000000 (40mHz). 

I made a $25 donation to Médecins Sans Frontières today. Thank you for your help. 

![image](https://user-images.githubusercontent.com/56199831/127691081-b6175f81-4088-4a19-ae8d-cd0e6e026779.png)

**Comment by RobTillaart** [comment]
I'm pretty close to having all functionality in the experimental branch

- switching between HSPI / VSPI with default pins on ESP32 in case of HWSPI
- added **setGPIOpins()** for overruling the default pins of the chosen HSPI / VSPI 
- added **SPISettings(...)** variable to optimize AVR
- optimized **swSPI_transfer()**
- optimized **triggerLatch()** 

Are there any questions left that need to be solved in this issue?

**Comment by HankLloydRight** [comment]
I can't think of a single thing.  
Thank you again.

**Comment by RobTillaart** [comment]
@HankLloydRight 
Read the https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/spi_master.html#gpio-matrix-and-io-mux  again, and I came across this line

```
Allows signals with clock frequencies only up to 40 MHz, as opposed to 80 MHz if IO_MUX pins are used.
```

If I interpret it correctly it could mean that the hardware HSPI / VSPI  could be set to 80 MHz if the default pins are used.
Might be worth a try to squeeze the performance...

(dived into this topic again because of a new issue)
